# Travis-CI Build for OpenRA
# see travis-ci.org for details

language: csharp
mono: 4.6.1

# http://docs.travis-ci.com/user/migrating-from-legacy
sudo: false

cache:
  directories:
  - thirdparty/download

addons:
  apt:
    packages:
    - lua5.1
    - nsis
    - nsis-common
    - dpkg
    - markdown

# Environment variables
env:

# Fetch dependencies
# Run the build script
# Check source code with StyleCop
# call OpenRA to check for YAML errors
# Run the NUnit tests
script:
 - travis_retry make all-dependencies
 - make all SDK="-sdk:4.5"
 - make check
 - make check-scripts
 - make test
 - make nunit

# Automatically update the trait documentation and Lua API
after_success:
 - test $TRAVIS_PULL_REQUEST == "false" && make docs && cd packaging && ./update-wiki.sh $TRAVIS_BRANCH; cd ..

# Only watch the development branch and tagged release.
branches:
 only:
   - /^cd-release-.*$/
   - cd

# Notify developers when build passed/failed.
notifications:

before_deploy:
 - export PATH=$PATH:$HOME/usr/bin
 - DOTVERSION=`echo ${TRAVIS_TAG} | sed "s/-/\\./g"`
 - cd packaging
 - mkdir build
 - ./package-all.sh ${TRAVIS_TAG} ${PWD}/build/
deploy:
  provider: releases
  api_key:
    secure: NrwdXHkz0lPvYoBJpIbrYzyi4ByjO0IZdwAUv7SoAkopGy3fums33o601ixX+OyFpRjFPRRSxnMUIJJDqkv7/6HZCGAgzvVkiy0nX3Bwog7W07YmpHR7FjQociQW+RK2n+wYwTeEX8ib747fkT2xzYaxnIvanSEQxSK9JKGiqvSnTdvZl6axe+sSWjyM/f3cPrgtakalxBD7BHEUEB7BwMs9UGXOiiHwPIYsOnRnDz6MhEgJ4Yx8hUy4Fh+5RJETIBIov1Uok3Tia7kfTMtbuNN+llaW/cLBjDWNt2rmjQpyQ9nwxolTAcgdCzaQIUzklX1lnbyaH6l5TaYi8SQc5FJRcYavKWFD7t5VYtx+Gbbq3jmebh84nLmlZLniBjOvxBMO2Iq6LD68jO8GuMmeNH3yBPBQ1+LHfCKS6uOFqi+QZsqJPyeU+owjTK3ltVIqWZK1Ta5LJ68hgDijvfEzSjD4XuxWpiXKPZYOomQK60aC3HONVND7Lz2UkBRcR6M0bzmxoiwrPwHN3ul4QorCgX3WlYS3G5gpuxc9FylpCSwIVe6iThvmsbNg+oVt1UgJEAwuqawwf5M0EMzHArMxU1BFJgqqY/lw1zf+O2KMWJn5d9YSD3Z3pUfZThtfALksTLGglbaEnQbUM+8VTi0iBZmzGYVkw0yqGW4nQ+jAKyA=
  file:
    - build/OpenRA-${TRAVIS_TAG}.zip
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: jrb0001/OpenRA
